List Viacoin (VIA)
bisq-network/bisq-assets pull request #92
Opened 2018-08-03 14:19 UTC by romanornr

Official project URL: https://viacoin.org
Official block explorer URL: https://explorer.viacoin.org

third party block explorer URL: https://chainz.cryptoid.info/via/

2018-08-13 13:35 UTC, blabno requested changes
NACK per comments

2018-08-13 13:35 UTC, blabno commented on src/test/java/bisq/asset/coins/ViacoinTest.java
> +        //assertValidAddress("via1q95qlu98cpj23xy6w9tdnfn65n5vkpkey99g6wl"); bech32 for in the future
Remove commented out code.

2018-08-13 16:56 UTC, romanornr commented on src/test/java/bisq/asset/coins/ViacoinTest.java
> +        //assertValidAddress("via1q95qlu98cpj23xy6w9tdnfn65n5vkpkey99g6wl"); bech32 for in the future
I removed the commented out coded.

2018-08-17 09:28 UTC, romanornr commented
I removed the comments.

2018-08-25 23:52 UTC, romanornr commented
Any update about this?

2018-08-27 09:01 UTC, cbeams approved these changes
ACK. Note that merges are on hold until the resolution of https://github.com/bisq-network/proposals/issues/35. Please track that issue to stay up to date.

2018-09-06 15:37 UTC, cbeams commented
This repository has been moved into the 'assets' directory of the https://github.com/bisq-network/bisq repository. Please resubmit this pull request against that repository. See https://github.com/bisq-network/bisq-docs/pull/84 for updated instructions. When submitting your pull request, please mention in the description (a) that this is a resubmission, (b) paste a link back to this original pull request, and (c) whether the original had already bee ACKed. Thank you.

2018-09-06 15:37 UTC, closed without merging